apiVersion: v1
kind: ConfigMap
metadata:
  name: configs
  namespace: c04
data:
  application.yaml: |
    server:
      port: 9000
    spring:
      main:
        allow-circular-references: true
        allow-bean-definition-overriding: true
      datasource:
        url: jdbc:oracle:thin:@172.16.103.11:1521/C04PDB
        username: qtud
        password: Gtelpkt1122
        driver-class-name: oracle.jdbc.OracleDriver
      jpa:
        hibernate:
          ddl-auto: none
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.OracleDialect

    logging:
      level:
        root: INFO
    redis:
      config-file: /otp/app/configs/redis-sentinel.yaml
    system:
      configurations:
        cors:
          allow-credentials: true
          allowed-methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          allowed-header:
            - Authorization
            - Origin
            - Content-Type
            - Accept
            - Accept-Encoding
            - Accept-Language
            - Access-Control-Allow-Origin
            - Access-Control-Allow-Headers
            - Access-Control-Request-Method
            - X-Requested-With
            - X-Auth-Token
            - X-Xsrf-Token
            - Cache-Control
            - Id-Token
          exposed-header:
            - X-Xsrf-Token
          url-based-pattern-cors-configuration-source: '/**'
          allowed-origin-pattern:
            - http://qlcscn.c04.bca
            - https://qlcscn.c04.bca
        uri-white-list:
          - '/swagger-ui.html'
          - '/swagger/*'
          - '/swagger-ui/*'
          - '/swagger/v3/api/docs'
          - '/swagger/v3/api/docs/*'
          - '/v3/api-docs'
          - '/v3/api-docs/*'
          - '/login'
          - '/sign-up'
          - '/public/**'
          - '/introspect'