apiVersion: apps/v1
kind: Deployment
metadata:
  name: qtud-sso
  namespace: c04
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qtud-sso
  template:
    metadata:
      labels:
        app: qtud-sso
    spec:
      volumes:
        - name: logs
          emptyDir: { }
      containers:
        - name: qtud-sso
          image: registry.gtelsoft.vn/c04/qtud:1.1
          ports:
            - containerPort: 9000
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: logs
              mountPath: /app/logs
      restartPolicy: Always
      imagePullSecrets:
        - name: docker-registry